export const Wind = [
    {
        min_speed: 0,
        max_speed: 0.5,
        name: 'Calm',
        description: 'Smoke rises vertically',
        color: '#000000',
    },
    {
        min_speed: 0.6,
        max_speed: 1.5,
        name: 'Light air',
        description: 'Direction shown by smoke drift but not by wind vanes',
        color: '#aef1f9',
    },
    {
        min_speed: 1.6,
        max_speed: 3.3,
        name: 'Light breeze',
        description: 'Wind felt on face; leaves rustle; wind vane moved by wind',
        color: '#96f7dc',
    },
    {
        min_speed: 3.4,
        max_speed: 5.5,
        name: 'Gentle breeze',
        description: 'Leaves and small twigs in constant motion; light flags extended',
        color: '#96f7b4',
    },
    {
        min_speed: 5.6,
        max_speed: 7.9,
        name: 'Moderate breeze',
        description: 'Raises dust and loose paper; small branches moved',
        color: '#6ff46f',
    },
    {
        min_speed: 8.0,
        max_speed: 10.7,
        name: 'Fresh breeze',
        description: 'Small trees in leaf begin to sway; crested wavelets form on inland waters',
        color: '#73ed12',
    },
    {
        min_speed: 10.8,
        max_speed: 13.8,
        name: 'Strong breeze',
        description: 'Large branches in motion; whistling heard in telegraph wires; umbrellas used with difficulty',
        color: '#a4ed12',
    },
    {
        min_speed: 13.9,
        max_speed: 17.1,
        name: 'High wind',
        description: 'Whole trees in motion; inconvenience felt when walking against the wind',
        color: '#daed12',
    },
    {
        min_speed: 17.2,
        max_speed: 20.7,
        name: 'Gale',
        description: 'Twigs break off trees; generally impedes progress',
        color: '#edc212',
    },
    {
        min_speed: 20.8,
        max_speed: 24.4,
        name: 'Strong gale',
        description: 'Slight structural damage (chimney pots and slates removed)',
        color: '#ed8f12',
    },
    {
        min_speed: 24.5,
        max_speed: 28.4,
        name: 'Storm',
        description: 'Seldom experienced inland; trees uprooted; considerable structural damage',
        color: '#ed6312',
    },
    {
        min_speed: 28.5,
        max_speed: 32.6,
        name: 'Violent storm',
        description: 'Very rarely experienced; accompanied by widespread damage',
        color: '#ed2912',
    },
    {
        min_speed: 32.7,
        max_speed: 100,
        name: 'Hurricane',
        description: 'Devastation',
        color: '#d5102d',
    },
];
